# Generated by Django 3.2.13 on 2022-06-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_my_article_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_article',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
