# Generated by Django 3.2.13 on 2022-05-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10, unique=True, verbose_name='用户名')),
                ('user_account', models.CharField(max_length=10, unique=True, verbose_name='用户账号')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
            ],
        ),
    ]
