# Generated by Django 3.2.13 on 2022-06-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220601_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_user',
            name='password',
            field=models.CharField(max_length=100, verbose_name='密码'),
        ),
    ]
