# Generated by Django 3.2.13 on 2022-06-06 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_my_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_imge', models.ImageField(upload_to='images/avatar')),
                ('background_image', models.ImageField(upload_to='images/background')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.my_user')),
            ],
        ),
    ]
