# Generated by Django 3.2.13 on 2022-06-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_my_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='My_images',
            new_name='My_image',
        ),
    ]
