# Generated by Django 3.2.13 on 2022-06-06 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_my_images_my_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_image',
            old_name='avatar_imge',
            new_name='avatar_image',
        ),
    ]
